### ISSUE TITLE
Attribute Error trying to run Google Compute API in Python

### ISSUE THREAD

**Issue by yahavb** [GoogleCloudPlatform/compute-getting-started-python#10] opened 2015-07-30 21:22 UTC
I am not sure if it a general issue or mine only. 
When I executed the main.py after performing all the steps in the README I got the following error:

```
    body = urllib.parse.urlencode({
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlencode'
```

I rollback the google-api-client to 1.3.2 and it all works. 

```
sudo pip install -I google-api-python-client==1.3.2
```

Not sure if the issue should be submitted here or elsewhere. 

Thank you for your great code samples!

**Comment by jonparrott** [comment] 2015-07-30 21:30
This is most often due to a conflicting version of ``six`` included in OS X Python. I highly recommend that you use [virtualenv](https://virtualenv.pypa.io) basically always.

A quick crash-course for you and anyone else that runs into this issue.:
```bash
# install virtualenv globally.
sudo pip install virtualenv
# create a new virtualenv in the "env" directory.
virtualenv env
# activate the virtualenv
source env/bin/activate
# install the requirements into the virtualenv
pip install -r requirements.txt
# run the app/sample
python main.py
# exit the virtualenv
deactivate
```

**Comment by jonparrott** [comment] 2015-07-30 21:31
I'm closing this issue, if you find that the virtualenv method does not work for you, please let me know.

**Closed by jonparrott** 2015-07-30 21:31 UTC

**Comment by jonparrott** [comment] 2015-07-30 21:33
Duplicate of #9 as well. For future reference.

**Comment by yahavb** [comment] 2015-07-30 22:04
Thank you this is super helpful !

-yahav

On Jul 30, 2015, at 2:31 PM, Jonathan Wayne Parrott <notifications@github.com<mailto:notifications@github.com>> wrote:


This is most often due to a conflicting version of six included in OS X Python. I highly recommend that you use virtualenv<https://virtualenv.pypa.io> basically always.

A quick crash-course for you and anyone else that runs into this issue.:

# install virtualenv globally.
sudo pip install virtualenv
# create a new virtualenv in the "env" directory.
virtualenv env
# activate the virtualenv
source env/bin/activate
# install the requirements into the virtualenv
pip install -r requirements.txt
# run the app/sample
python main.py
# exit the virtualenv
deactivate

-
